apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "com.kaltura.kflow"
        minSdkVersion 23
        //noinspection EditedTargetSdkVersion
        targetSdkVersion 36
        versionCode 16
        versionName "4.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    namespace 'com.kaltura.kflow'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = "1.8"
        targetCompatibility = "1.8"
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }

}

android.applicationVariants.configureEach { variant ->
    variant.outputs.configureEach {
        outputFileName = "KFlow-v${variant.versionName} (${variant.versionCode}).apk"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.work:work-runtime-ktx:2.11.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    // Android
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.dynamicanimation:dynamicanimation:1.0.0'
    implementation 'androidx.security:security-crypto:1.1.0'

    // Navigation
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.6'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.6'

    // Koin
    implementation 'io.insert-koin:koin-androidx-viewmodel:2.2.3'
    implementation 'io.insert-koin:koin-androidx-scope:2.2.3'

    // Loading button
//    implementation 'br.com.simplepass:loading-button-android:2.2.0'
    implementation("com.github.leandroborgesferreira:loading-button-android:2.3.0")

    // Client library
    implementation 'com.kaltura:KalturaOttAndroidJavaClient:8.0.0.30025'

    // Playkit

    implementation 'com.kaltura.player:tvplayer:5.0.3'
//    implementation 'com.kaltura.playkit:playkitproviders:4.30.10'
//    implementation 'com.kaltura.playkit:youboraplugin:4.30.10'
//    implementation 'com.kaltura.playkit:kavaplugin:4.30.10'
//    implementation 'com.kaltura.playkit:vrplugin:4.30.10'

    // Firebase
    implementation 'com.google.firebase:firebase-analytics:23.0.0'
    implementation platform('com.google.firebase:firebase-bom:34.8.0')
    implementation 'com.google.firebase:firebase-messaging'

    // AWS IoT
    implementation 'com.amazonaws:aws-android-sdk-iot:2.81.1'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.81.1'
}
